
GET localhost:8080/u/r/all

###
POST http://localhost:8080/u/new
Content-Type: application/json

{
  "email": "a@gmail.com",
  "password": "abc",
  "fullName": "abcd",
  "poblacio": "1234",
  "id": 1,
  "racha": 3
}

###
GET http://localhost:8080/get?email=a@gmail.com